finbourne/lusid-sdk-java-preview

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Holdings.java
sdk/src/test/java/com/finbourne/lusid/utilities/ApiExceptionTests.java

TR-282: Fix API Funcs

---

sdk/lusid-sdk-preview.iml
sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Valuation.java

DEV-5134 Migrate to QuotesApi

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java

Add paging support for "List portfolios for scope" function

DEV-5935: Support paging for ListPortfoliosForScope

---

sdk/src/test/java/com/finbourne/lusid/tutorials/marketdata/Instruments.java

Update test for paged instruments

DEV-3742 Update test for paged instruments

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Orders.java

First set of tests for new Orders endpoints

DEV-6756: first entry for Orders java tests.

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Orders.java

DEV-6760: updated tests

---

sdk/Dockerfile

Update base image for tests which is no longer working with jq

DEV-7399 update mvn test image

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Orders.java

This reverts commit 59221c6e99ed5ddafdff2cebaa6781feb8b63da5.
Reverts recent changes

Revert "DEV-7485: updated to handle new orders api"

---

sdk/pom.xml

DEV-7032 Updates for OpenAPI generator 4.3.0

---

sdk/pom.xml

Reverts finbourne/lusid-sdk-java-preview#41

Revert "DEV-7032 Updates for OpenAPI generator 4.3.0"

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Orders.java

This reverts commit 20c35fc99c99e40c743b7ff3cf524eba834a1d46.
Reapplication of previous PR.

DEV-7485: updated to handle new orders api. Second attempt.

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Holdings.java

DEV-6524: Add new optional param for AdjustHolding

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Orders.java

Revert: SDK change ok but performance problems server side on ListOrders.

DEV-7485: revert SDK update

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Valuation.java

DEV-7749 OpenApi Tests

---

sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Valuation.java

DEV-8335: Changing test to use new aggregation endpoint

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Orders.java

Only try to get the first 3 orders back, rather than going for everything and downfiltering.

DEV-8242: reduce aspirations of failing Java tutorial/integration test

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Orders.java

Am not expecting a performance improvement until we move to using the property warehouse, get a derived entity index or start using relations to express order->allocation relationships.

DEV-8242: ignore intermittently long-running test

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Properties.java

- [x ] Read the [contributing guidelines](../docs/CONTRIBUTING.md)
Added properties.java file

SE-109 Add Properties Examples

---

sdk/lusid-sdk-preview.iml
sdk/src/test/unit/java/com/finbourne/lusid/utilities/InstrumentLoader.java

SE-242 Remove unused code

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Transactions.java

Adds an example of cancelling transactions.

Se 1018 cancel tx

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Valuation.java

Migrate aggregation to valuation endpoint

SE-1090 Migrate aggregation to valuation endpoint

---

sdk/src/test/integration/java/com/finbourne/lusid/utilities/LusidApiFactoryBuilderTests.java

SE-1131 Remove call to ScopesApi

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java

- [] Raised the PR against the `develop` branch
Temporarily disable change

PLAT-285 temporarily disable test

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Bitemporal.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Transactions.java

Update GetTransaction endpoint for pagination

---

sdk/src/main/java/com/finbourne/lusid/utilities/RefreshingTokenApiClient.java

Change in ApiClient signature

---

sdk/src/main/java/com/finbourne/lusid/utilities/RefreshingTokenApiClient.java

Reverts finbourne/lusid-sdk-java-preview#99

Revert "Change in ApiClient signature"

---

sdk/src/main/java/com/finbourne/lusid/utilities/RefreshingTokenApiClient.java

Open api take2

---

sdk/src/main/java/com/finbourne/lusid/utilities/RefreshingTokenApiClient.java

Reverts finbourne/lusid-sdk-java-preview#101

Revert "Open api take2"

---

sdk/src/test/unit/java/com/finbourne/lusid/utilities/RefreshingTokenApiClientTest.java

Compilation issue on tests

---

sdk/pom.xml
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Bitemporal.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Holdings.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Properties.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Reconciliation.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Transactions.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Valuation.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/marketdata/Quotes.java
sdk/src/test/unit/java/com/finbourne/lusid/utilities/TestDataUtilities.java

Migrate from `Double` to `BigDecimal`

CTECH-1018 Migrate to BigDecimal

---

sdk/src/main/java/com/finbourne/lusid/utilities/ApiClientBuilder.java
sdk/src/main/java/com/finbourne/lusid/utilities/HttpClientFactory.java
sdk/src/main/java/com/finbourne/lusid/utilities/LusidApiFactoryBuilder.java
sdk/src/test/integration/java/com/finbourne/lusid/utilities/ApiClientBuilderTests.java
sdk/src/test/unit/java/com/finbourne/lusid/utilities/ApiClientBuilderTest.java

Fix adding support for read/write timeouts

CTECH-1336 fix timeouts

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Orders.java

Update orders examples to BigDecimal. Tests pass local version

DEV-9271 Update orders examples to BigDecimal

---

.gitignore
sdk/src/main/java/com/finbourne/lusid/utilities/auth/RefreshingTokenProvider.java
sdk/src/test/integration/java/com/finbourne/lusid/utilities/auth/RefreshingTokenProviderTests.java
sdk/src/test/unit/java/com/finbourne/lusid/utilities/auth/RefreshingTokenProviderTest.java

Adds additional logging for the root exception when failing to get a refresh token

CTECH-1896 Enable logging of root exception when refresh token fails

---

sdk/pom.xml

CTECH-1911 Fix dependabot alerts

---

sdk/src/main/java/com/finbourne/lusid/utilities/ApiClientBuilder.java
sdk/src/main/java/com/finbourne/lusid/utilities/HttpClientFactory.java
sdk/src/main/java/com/finbourne/lusid/utilities/LusidApiFactoryBuilder.java
sdk/src/test/integration/java/com/finbourne/lusid/utilities/ApiClientBuilderTests.java

Add configurable connection timeout

CTECH-2025 add configurable connection timeout 

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/marketdata/Instruments.java

increase timeout to 30s for instruments api

CTECH-1367 increase timeout to 30s for instruments api

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/marketdata/Instruments.java
sdk/src/test/unit/java/com/finbourne/lusid/utilities/InstrumentLoader.java

Update the list of instruments used in examples

CTECH-2828 update instruments used in examples

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/marketdata/Instruments.java

- [ x] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [ x] Tests pass
- [ x] Raised the PR against the `develop` branch

PLAT-2588: Add new field to getPropertyDefinition

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java

PLAT-2838 remove list portfolio param

---

sdk/src/main/java/com/finbourne/lusid/utilities/HttpClientFactory.java

CTECH-3307: Resolve Proxy IPs on each call

---

sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Bitemporal.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java
sdk/src/test/tutorial/java/com/finbourne/lusid/tutorials/ibor/Transactions.java

- [ x] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [~ ] Tests pass
- [ x] Raised the PR against the `develop` branch
Added sortBy parameter to GetTransactions endpoint in Lusid, so will need adding here for SDK tests

Added sortBy field for GetTransactions in tests
